$(function(){
  $(".Open").click(function(){
      if($(".navList_content").css("right")=="0px"){
        $(".navList_content").animate({"right":"8rem"});
        $(".wrap_sum").css("overflow","hidden");
      }else{
        $(".navList_content").animate({"right":"0px"});
        $(".wrap_sum").css("overflow","auto");
      }
    })
})
$(function(){
  $(".navList_head").click(function(){
      $(this).siblings("dd").show();
      $(this).addClass("navList_up");
      $(this).parents("dl").siblings("dl").children("dd").hide();
      $(this).parents("dl").siblings("dl").children("dt").removeClass("navList_up");
    })
})

